export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";
export const REQUEST_FAILED = "REQUEST_FAILED";

export const AUTH = "AUTH";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const START_AUTH_LOADING = "START_AUTH_LOADING";
export const END_AUTH_LOADING = "END_REGISTER_LOADING";

export const REGISTER = "REGISTER";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const START_REGISTER_LOADING = "START_REGISTER_LOADING";
export const END_REGISTER_LOADING = "END_REGISTER_LOADING";

export const START_UPDATE_USER_LOADING = "START_UPDATE_USER_LOADING";
export const UPDATE_USER = "UPDATE_USER";
export const END_UPDATE_USER_LOADING = "END_UPDATE_USER_LOADING";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const USER_DETAILS = "USER_DETAILS";
export const START_USER_DETAILS_LOADING = "START_USER_DETAILS_LOADING";
export const END_USER_DETAILS_LOADING = "END_USER_DETAILS_LOADING";
export const USER_DETAILS_FAILURE = "USER_DETAILS_FAILURE";

export const VERIFY_USER = "VERIFY_USER";
export const START_VERIFY_USER_LOADING = "START_VERIFY_USER_LOADING";
export const END_VERIFY_USER_LOADING = "END_VERIFY_USER_LOADING";
export const VERIFY_USER_FAILURE = "VERIFY_USER_FAILURE";

export const RESEND_LINK = "RESEND_LINK";
export const START_RESEND_LINK_LOADING = "START_RESEND_LINK_LOADING";
export const END_RESEND_LINK_LOADING = "END_RESEND_LINK_LOADING";
export const RESEND_LINK_FAILURE = "RESEND_LINK_FAILURE";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const START_FORGOT_PASSWORD_LOADING = "START_FORGOT_PASSWORD_LOADING";
export const END_FORGOT_PASSWORD_LOADING = "END_FORGOT_PASSWORD_LOADING";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const START_RESET_PASSWORD_LOADING = "START_RESET_PASSWORD_LOADING";
export const END_RESET_PASSWORD_LOADING = "END_RESET_PASSWORD_LOADING";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export const LOGOUT = "LOGOUT";

export const START_USER_TEAMS_LOADING = "START_USER_TEAMS_LOADING";
export const USER_TEAMS = "USER_TEAMS";
export const END_USER_TEAMS_LOADING = "END_USER_TEAMS_LOADING";
export const USER_TEAMS_FAILURE = "USER_TEAMS_FAILURE";

export const START_GET_USER_LOADING = "START_GET_USER_LOADING";
export const GET_USER = "GET_USER";
export const END_GET_USER_LOADING = "END_GET_USER_LOADING";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const GET_FRIENDS = "GET_FRIENDS";
export const START_GET_FRIENDS_LOADING = "START_GET_FRIENDS_LOADING";
export const END_GET_FRIENDS_LOADING = "END_GET_FRIENDS_LOADING";
export const GET_FRIENDS_FAILURE = "GET_FRIENDS_FAILURE";

export const START_GET_USERS_LOADING = "START_GET_USERS_LOADING";
export const GET_USERS = "GET_USERS";
export const END_GET_USERS_LOADING = "END_GET_USERS_LOADING";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const START_GET_TEAM_LOADING = "START_GET_TEAM_LOADING";
export const GET_TEAM = "GET_TEAM";
export const END_GET_TEAM_LOADING = "END_GET_TEAM_LOADING";
export const GET_TEAM_FAILURE = "GET_TEAM_FAILURE";

export const START_GET_TEAMS_LOADING = "START_GET_TEAM_LOADING";
export const GET_TEAMS = "GET_TEAM";
export const END_GET_TEAMS_LOADING = "END_GET_TEAM_LOADING";
export const GET_TEAMS_FAILURE = "GET_TEAM_FAILURE";

export const START_POST_LOADING = "START_POST_LOADING";
export const POST = "POST";
export const END_POST_LOADING = "END_POST_LOADING";
export const POST_FAILURE = "POST_FAILURE";

export const START_POSTS_LOADING = "START_POSTS_LOADING";
export const POSTS = "POSTS";
export const END_POSTS_LOADING = "END_POSTS_LOADING";
export const POSTS_FAILURE = "POSTS_FAILURE";

export const ADD_FRIEND = "ADD_FRIEND";
export const START_INVITE_LOADING = "START_INVITE_LOADING";
export const END_INVITE_LOADING = "END_INVITE_LOADING";
export const GET_INVITES = "GET_INVITES";
export const ACCEPT_INVITE = "ACCEPT_INVITE";
export const DELETE_INVITE = "DELETE_INVITE";
