export const GET_GROUP_INVITES = "GET_GROUP_INVITES";
export const START_GROUP_INVITE_LOADING = "START_GROUP_INVITE_LOADING";
export const END_GROUP_INVITE_LOADING = "END_GROUP_INVITE_LOADING";
export const GET_GROUP_INVITE_FAILURE = "GET_GROUP_INVITE_FAILURE";
export const ACCEPT_GROUP_INVITE = "ACCEPT_GROUP_INVITE";
export const DECLINE_GROUP_INVITE = "DECLINE_GROUP_INVITE";
export const DELETE_USER = "DELETE_USER";
export const CREATE_TEAM = "CREATE_TEAM";
